### ISSUE TITLE
manticore jar conflict when installed with elasticsearch-ec2 output

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-output-elasticsearch_http#2]
specs fails when all plugins are installed:
```
LogStash::Outputs::ElasticsearchHTTP#register should register
Failure/Error: expect { subject.register }.to_not raise_error
  expected no Exception, got #<LoadError: load error: manticore -- java.lang.NoSuchFieldError: INSTANCE> with backtrace:
```

per cheald/manticore#2 this is an indication of a conflict with the httpcore jar. In fact, these are the httpcore jars installed when all plugins are installed:

```
vendor/bundle/jruby/1.9/gems/jruby-httpclient-1.1.1-java/vendor/httpcore-4.1.jar
vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-ec2-0.2.2/lib/org/apache/httpcomponents/httpcore/4.2/httpcore-4.2.jar
vendor/bundle/jruby/1.9/gems/manticore-0.3.6-java/lib/jar/httpcore-4.3.3.jar
```

The exception is not raised when running specs in isolation, which leads me to believe that the `jruby-httpclient-1.1.1-java` gem, a runtime dependency of logstash-core, is actually not used in logstash-core. Will file another issue to asses this.

The problem is thus an httpcore jar conflict with the **logstash-output-elasticsearch-ec2** plugins.

**Comment by ph** [comment]
Good catch, This plugin is a shim and I am a bit surprised we don't have this issue with the actual output-elasticseach?

**Comment by colinsurprenant** [comment]
@jsvd FYI

**Comment by jsvd** [comment]
This doesn't happen with logstash-output-elasticsearch because the [register test in that plugin](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/spec/outputs/elasticsearch_spec.rb#L9-L14) uses transport instead of http:

```ruby
  it "should register" do
    output = LogStash::Plugin.lookup("output", "elasticsearch").new("embedded" => "false", "protocol" => "transport", "manage_template" => "false")

    # register will try to load jars and raise if it cannot find jars
    expect {output.register}.to_not raise_error
  end
```

Investigating..

**Comment by colinsurprenant** [comment]
ah yes, then we should definitely test both to trigger jar conflicts

**Comment by jsvd** [comment]
I can't find a decent solution to this without forcing either side to upgrade, any ideas?

**Comment by colinsurprenant** [comment]
I don't think we can do any magic here...

**Comment by cheald** [comment]
Author of Manticore here. This is an issue that I've been trying to find a solution to. Unfortunately, there's not really a great mechanism for resolving jar conflicts in Rubygems right now, leaving projects to manage dependenceis manually. It's a giant pain.

If anyone has suggestions as to how to address this, I'd love to work towards a solution.

**Comment by jsvd** [comment]
worked around by including the jars inside of the logstash plugins, allowing us to upgrade the httpcore/httpclient versions in the elasticsearch-aws plugin to match manticore's.
Closing
